worlds:
    - name   : world       # The name of a world to apply giant caves
      fxz    : 0.005       # Perlin noise frequency in the horizontal plane (smaller number = wider cave)
      fy     : 0.01        # Perlin noise frequency in the vertical dimension (smaller number = taller cave)
      cutoff : 62          # Minimum Perlin density cutoff (-100 to 100)
      miny   : 6           # Lower bound of cave zone
      maxy   : 64          # Uppoer bound of cave zone
      debug  : false       # Turns on invert mode for experimenting with config values (true/false)